[project]
name = "mujoco-ppo-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "brax>=0.14.0",
    "click>=8.3.1",
    "flax>=0.12.3",
    "imageio[ffmpeg]>=2.37.2",
    "jax>=0.9.0",
    "mlflow>=3.9.0",
    "playground>=0.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
